### ISSUE TITLE
Drop all tables at the same command

### ISSUE THREAD

**Issue by veredrec** [FACN3/SecretSanta#58]
Instead of 
`DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS gifts CASCADE;
DROP TABLE IF EXISTS relationship CASCADE;
DROP TABLE IF EXISTS reservation CASCADE;`

You can simply write 
`DROP TABLE IF EXISTS users, gifts, relationship, reservation CASCADE;`

**Comment by MynahMarie** [comment]
Done! :)

**Comment by veredrec** [comment]
@MynahMarie did you push it to github? Because it still appears in the old version...
